/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiKitchenIndexRouteImport } from './routes/ai-kitchen.index'
import { Route as AiKitchenAhorroRouteImport } from './routes/ai-kitchen.ahorro'
import { Route as AiKitchenCrearRecetaRouteImport } from './routes/ai-kitchen.crear-receta'
import { Route as AiKitchenHazloEnCasaRouteImport } from './routes/ai-kitchen.hazlo-en-casa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiKitchenIndexRoute = AiKitchenIndexRouteImport.update({
  id: '/ai-kitchen/',
  path: '/ai-kitchen/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiKitchenAhorroRoute = AiKitchenAhorroRouteImport.update({
  id: '/ai-kitchen/ahorro',
  path: '/ai-kitchen/ahorro',
  getParentRoute: () => rootRouteImport,
} as any)
const AiKitchenCrearRecetaRoute = AiKitchenCrearRecetaRouteImport.update({
  id: '/ai-kitchen/crear-receta',
  path: '/ai-kitchen/crear-receta',
  getParentRoute: () => rootRouteImport,
} as any)
const AiKitchenHazloEnCasaRoute = AiKitchenHazloEnCasaRouteImport.update({
  id: '/ai-kitchen/hazlo-en-casa',
  path: '/ai-kitchen/hazlo-en-casa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-kitchen/ahorro': typeof AiKitchenAhorroRoute
  '/ai-kitchen/crear-receta': typeof AiKitchenCrearRecetaRoute
  '/ai-kitchen/hazlo-en-casa': typeof AiKitchenHazloEnCasaRoute
  '/ai-kitchen/': typeof AiKitchenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-kitchen/ahorro': typeof AiKitchenAhorroRoute
  '/ai-kitchen/crear-receta': typeof AiKitchenCrearRecetaRoute
  '/ai-kitchen/hazlo-en-casa': typeof AiKitchenHazloEnCasaRoute
  '/ai-kitchen': typeof AiKitchenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-kitchen/ahorro': typeof AiKitchenAhorroRoute
  '/ai-kitchen/crear-receta': typeof AiKitchenCrearRecetaRoute
  '/ai-kitchen/hazlo-en-casa': typeof AiKitchenHazloEnCasaRoute
  '/ai-kitchen/': typeof AiKitchenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-kitchen/ahorro'
    | '/ai-kitchen/crear-receta'
    | '/ai-kitchen/hazlo-en-casa'
    | '/ai-kitchen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-kitchen/ahorro'
    | '/ai-kitchen/crear-receta'
    | '/ai-kitchen/hazlo-en-casa'
    | '/ai-kitchen'
  id:
    | '__root__'
    | '/'
    | '/ai-kitchen/ahorro'
    | '/ai-kitchen/crear-receta'
    | '/ai-kitchen/hazlo-en-casa'
    | '/ai-kitchen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiKitchenAhorroRoute: typeof AiKitchenAhorroRoute
  AiKitchenCrearRecetaRoute: typeof AiKitchenCrearRecetaRoute
  AiKitchenHazloEnCasaRoute: typeof AiKitchenHazloEnCasaRoute
  AiKitchenIndexRoute: typeof AiKitchenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-kitchen/': {
      id: '/ai-kitchen/'
      path: '/ai-kitchen'
      fullPath: '/ai-kitchen/'
      preLoaderRoute: typeof AiKitchenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-kitchen/ahorro': {
      id: '/ai-kitchen/ahorro'
      path: '/ai-kitchen/ahorro'
      fullPath: '/ai-kitchen/ahorro'
      preLoaderRoute: typeof AiKitchenAhorroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-kitchen/crear-receta': {
      id: '/ai-kitchen/crear-receta'
      path: '/ai-kitchen/crear-receta'
      fullPath: '/ai-kitchen/crear-receta'
      preLoaderRoute: typeof AiKitchenCrearRecetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-kitchen/hazlo-en-casa': {
      id: '/ai-kitchen/hazlo-en-casa'
      path: '/ai-kitchen/hazlo-en-casa'
      fullPath: '/ai-kitchen/hazlo-en-casa'
      preLoaderRoute: typeof AiKitchenHazloEnCasaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiKitchenAhorroRoute: AiKitchenAhorroRoute,
  AiKitchenCrearRecetaRoute: AiKitchenCrearRecetaRoute,
  AiKitchenHazloEnCasaRoute: AiKitchenHazloEnCasaRoute,
  AiKitchenIndexRoute: AiKitchenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
